seed = "291644223294089693482525371547067336816"
root_commitment = "0x106fb5db4267ff4f6a05a998734d952a97ef429fb35ac3bd59b2af34726c3b82"
cards = ["29", "33", "47", "19", "15", "14", "28", "31", "22", "40", "30", "25", "3", "17", "0"]
