[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_poker = "2fS8A3rSY5zSJyc5kaCKhAhwjpLiRPhth1bTwNWmGNcm"

[programs.devnet]
solana_poker = "2fS8A3rSY5zSJyc5kaCKhAhwjpLiRPhth1bTwNWmGNcm"
inco_lightning = "5sjEbPiqgZrYwR31ahR6Uk9wf5awoX61YGg7jExQSwaj"

[registry]
url = "https://devnet.helius-rpc.com/?api-key=19e8e7a6-48a7-405a-95d6-27123b062c3d"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=19e8e7a6-48a7-405a-95d6-27123b062c3d"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
